// Copyright (C) 2025 Savoir-faire Linux, Inc.
// SPDX-License-Identifier: CC-BY-4.0

Seapath live installer
======================
:toc:
:icons:
:iconsdir: ./doc/icons/
:sectnumlevels: 1

This is based on the Debian 12 live image. See the dedicated README for details
related to Debian live.
You can build this using https://github.com/savoirfairelinux/cqfd[cqfd]. More
details are given in the next sections of this document.

:numbered:

== Building a firmware using cqfd

`cqfd` is a quick and convenient way to run commands in the current directory,
but within a pre-defined Docker container. Using `cqfd` allows you to avoid
installing anything else than Docker on your development machine.

NOTE: We recommend using this method as it greatly simplifies the build
configuration management process.

=== Prerequisites

==== Docker installation

See docker manual: https://docs.docker.com/engine/install/[Install docker]

* Install cqfd:

if necessary install *make* and pkg-config packages.

For instance, with Ubuntu/Debian distribution:
`$ sudo apt-get install build-essential pkg-config`

then
```
$ git clone https://github.com/savoirfairelinux/cqfd.git
$ cd cqfd
$ sudo make install
```

The project page on https://github.com/savoirfairelinux/cqfd[Github] contains
detailed information on usage and installation.

* Make sure that docker does not require sudo

Please use the following commands to add your user account to the `docker`
group:

```
$ sudo groupadd docker
$ sudo usermod -aG docker $USER
```

Log out and log back in, so that your group membership can be re-evaluated.

==== SEAPATH installer

The Debian package created with the
https://g1.sfl.io/plugins/gitiles/sfl/seapath/seapath-installer/+/refs/heads/main[seapath-installer]
should be saved to `config/pakages.chroot` folder.

Visit the repository for more details on how to build the Debian package.

=== Building the firmware

The first step with `cqfd` is to create the build container. For this, use the
`cqfd init` command:

$ cqfd init

NOTE: The step above is only required once, as once the container image has been
created on your machine, it will become persistent. Further calls to `cqfd init`
will do nothing, unless the container definition (`.cqfd/docker/Dockerfile`) has
changed in the source tree.u* Debian package of Seapath-installer

cqfd provides `sfl_ci` flavor that allows to call build.sh. Run:

$ cqfd -b sfl_ci


== About this documentation

This documentation uses the AsciiDoc documentation generator. It is a convenient
format that allows using plain-text formatted writing that can later be
converted to various output formats such as HTML and PDF.

In order to generate an HTML version of this documentation, use the following
command (the asciidoc package will need to be installed in your Linux
distribution):

$ asciidoc README.adoc

This will result in a README.html file being generated in the current directory.

If you prefer a PDF version of the documentation instead, use the following
command (the dblatex package will need to be installed on your Linux
distribution):

$ asciidoctor-pdf README.adoc
